# Generated by Django 4.1.3 on 2022-11-15 04:37

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="pub_date",
            field=models.DateField(default=datetime.now),
            preserve_default=False,
        ),
    ]
