# Generated by Django 4.1.3 on 2022-11-15 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_movie_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="pub_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
