# Generated by Django 4.1.3 on 2022-11-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_alter_movie_cover"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="pub_date",),
    ]
