# Generated by Django 4.1.3 on 2022-11-15 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_remove_movie_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="pub_date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2022, 11, 15, 16, 9, 54, 524511)
            ),
        ),
    ]
