# Generated by Django 4.1.3 on 2022-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0009_alter_movie_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cover",
            field=models.FileField(blank=True, default=None, upload_to="covers/", null=True),
        ),
    ]
