# Generated by Django 4.1.3 on 2022-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0010_movie_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="cover",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="covers/"
            ),
        ),
    ]
